=== gs1oliot/gs1source/DataAggregator/target/source-1.0.0-BUILD-SNAPSHOT/WEB-INF/classes/org/gs1/source/schema/tsd/ProductAllergenInformationModule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:product_allergen_information_module="urn:gs1:tsd:product_allergen_information_module:xsd:1"
	xmlns:shared_common="urn:gs1:shared:shared_common:xsd:3"
	xmlns:tsd_common="urn:gs1:tsd:tsd_common:xsd:1"
	targetNamespace="urn:gs1:tsd:product_allergen_information_module:xsd:1"
	elementFormDefault="unqualified" attributeFormDefault="unqualified"
	version="1.1">
	<xsd:annotation>
		<xsd:documentation><![CDATA[---------------------------
Â© Copyright GS1, 2013

GS1 is providing this XML Schema Definition file and resultant XML file as a service to interested industries.
This XML Schema Definition file and resultant XML file were developed through a consensus process of interested parties.

Although efforts have been made to ensure that the XML Schema Definition file and resultant XML file are correct, reliable, and technically
accurate,  GS1 makes NO WARRANTY, EXPRESS OR IMPLIED, THAT THIS XML Schema Definition file and resultant XML file ARE
CORRECT, WILL NOT REQUIRE MODIFICATION AS EXPERIENCE AND TECHNOLOGICAL ADVANCES DICTATE, OR WILL BE SUITABLE FOR
ANY PURPOSE OR WORKABLE IN ANY APPLICATION, OR OTHERWISE.  Use of the XML Schema Definition file and resultant XML
file are with the understanding that GS1 has no liability for any claim to the contrary, or for any damage or loss of any kind or nature.

Version Information:
Version Number: 1.1
Date of creation: April 2013

The schema and subsequent updates will be provided on the GS1 websites.
---------------------------
]]></xsd:documentation>
	</xsd:annotation>
	<xsd:import namespace="urn:gs1:shared:shared_common:xsd:3"
		schemaLocation="../shared/SharedCommon.xsd" />
	<xsd:import namespace="urn:gs1:tsd:tsd_common:xsd:1"
		schemaLocation="TSDCommon.xsd" />
	<xsd:element name="productAllergenInformationModule"
		type="product_allergen_information_module:TSD_ProductAllergenInformationModuleType" />
	<xsd:complexType name="TSD_AllergenRelatedInformationType">
		<xsd:sequence>
			<xsd:element name="allergenStatement"
				type="tsd_common:TSD_FormattedDescription1000Type" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="allergenSpecificationAgency"
				minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="70" />
						<xsd:minLength value="1" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="allergenSpecificationName" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="70" />
						<xsd:minLength value="1" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="allergen"
				type="product_allergen_information_module:TSD_AllergenType"
				minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="avpList"
				type="tsd_common:TSD_AttributeValuePairListType" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TSD_AllergenType">
		<xsd:sequence>
			<xsd:element name="allergenTypeCode"
				type="product_allergen_information_module:TSD_AllergenTypeCodeType" />
			<xsd:element name="levelOfContainmentCode"
				type="product_allergen_information_module:TSD_LevelOfContainmentCodeType" />
			<xsd:element name="avpList"
				type="tsd_common:TSD_AttributeValuePairListType" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TSD_AllergenTypeCodeType">
		<xsd:simpleContent>
			<xsd:extension base="shared_common:GS1CodeType" />
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="TSD_LevelOfContainmentCodeType">
		<xsd:simpleContent>
			<xsd:extension base="shared_common:GS1CodeType" />
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="TSD_ProductAllergenInformationModuleType">
		<xsd:complexContent>
			<xsd:extension base="tsd_common:TSD_ModuleType">
				<xsd:sequence>
					<xsd:element name="allergenRelatedInformation"
						type="product_allergen_information_module:TSD_AllergenRelatedInformationType"
						maxOccurs="unbounded" />
					<xsd:element name="avpList"
						type="tsd_common:TSD_AttributeValuePairListType" minOccurs="0" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== gs1oliot/gs1source/DataAggregator/src/main/java/org/gs1/source/schema/tsd/ProductAllergenInformationModule.xml
<?xml version="1.0" encoding="UTF-8"?>
<product_allergen_information_module:productAllergenInformationModule xmlns:product_allergen_information_module="urn:gs1:tsd:product_allergen_information_module:xsd:1" xmlns:shared_common="urn:gs1:shared:shared_common:xsd:3" xmlns:tsd_common="urn:gs1:tsd:tsd_common:xsd:1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:gs1:tsd:product_allergen_information_module:xsd:1 ProductAllergenInformationModule.xsd ">
  <allergenRelatedInformation>
    <allergenStatement languageCode="en">allergenStatement</allergenStatement>
    <allergenSpecificationAgency>allergenSpecificationAgency</allergenSpecificationAgency>
    <allergenSpecificationName>allergenSpecificationName</allergenSpecificationName>
    <allergen>
      <allergenTypeCode>allergenTypeCode</allergenTypeCode>
      <levelOfContainmentCode>levelOfContainmentCode</levelOfContainmentCode>
    </allergen>
  </allergenRelatedInformation>
</product_allergen_information_module:productAllergenInformationModule>
